### ISSUE TITLE
Remeber to fix the atom error bug (ln 0)

### ISSUE THREAD

**Issue by kalscium** [ina-org/lexi#1]
A bug in which the 'strings with arrows' file is not able to generate a correct string response due to the position in the Error class to have the line of 0 which is problematic.

**Example**
```
<lexi>1 +

Token[ INT:1 ]
Token[ PLUS ]
Token[ EOF ]

Error[ Invalid Syntax: Expected int, float, identifier, string, '[', '{', '+', '-', or '(' ]
File[ <stdin> ], Line[ 1 ]

1 +
   
<lexi>
```

**Comment by GreenChild04** [comment]
A bug in which the 'strings with arrows' file is not able to generate a correct string response due to the position in the Error class to have the line of 0 which is problematic. 

**Example**
`
<lexi>1 +

Token[ INT:1 ]
Token[ PLUS ]
Token[ EOF ]

Error[ Invalid Syntax: Expected int, float, identifier, string, '[', '{', '+', '-', or '(' ]
File[ <stdin> ], Line[ 1 ]

1 +
   
<lexi>
`

**Comment by kalscium** [comment]
It appears the problem to not be due to the line being zero but due to another fundemental problem I had before the parser; inside the lexer. The problem was due to my 'quick fix' to the string and other tokens having positions idx being one to many; removing one of the '^' from the end. This was a bad fix since, for single character errors, it would just completely dissapear (see above).

I have solved this by using a copy of position and not the same class since it would be incremented afterwards due to the rolling lexer.
